### ISSUE TITLE
Use prior iteration solutions at initial guesses

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#177]
Let's try to store the solutions to the model from prior iterations of time path iteration (and perhaps the SS solution algorithm) to use as initial guesses in the current iteration.

In this way, we start closer to the true solution an so should speed up the computation.

**Comment by rickecon** [comment]
But we only want to use equilibrium solutions from past runs that have "close" parameterizations. I don't know of a good way to define "close" ex ante. However, @jdebacker is right that if we save solutions for parameterizations, we will eventually have a nice sparse grid that might even have enough points to interpolate solutions rather than solving the whole model.

**Comment by jdebacker** [comment]
In this issue I'm referring to guesses from a prior iteration of the same model run.

Consider that it takes about 20-30 iterations from TPI to converge.  The idea would be that iteration 2 of TPI uses the solutions from iteration 1 as its initial guess.  Currently, we use the same initial guess at the solution to the hh's problem in each iteration.  If we start closer to the solution, then the time it takes to solve the household's problem in each iteration will be faster.

One of @rickecon 's suggestions is to use the solution to a prior model run to inform the initial guess of iteration 1 of TPI.  In this case, he right that we'll need to be careful that parameterizations are similar.  Another suggestion is to store the output of the model runs and then use that to interpolate model solutions from those output files.  These are both pretty involved and let's save them for a future issue.

**Comment by jdebacker** [comment]
Superseded by issue #224
