### ISSUE TITLE
Frisch elasticity of labor supply, user defined values

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#185]
One of the inputs we intend to allow the user to manipulate is the Frisch elasticity of labor supply.  I've done some testing and given other parameter values, our model will only solve with a Frisch elasticity less than 0.9.  Note that our baseline is 0.4, which is a commonly used value.  However, peer-reviewed research has estimated Frisch elasticities from 0.1 to 6.0.

Can we constrain the user to pick a value in the 0.1 to 0.8 range so we can be more confident in model convergence?

As an aside, we technically should be changing some other parameters when the Frisch elasticity (or a set of other parameters) changes.  However, the method to reestimate these parameters does not appear very robust and would add significant computational time even if it were robust.  In the future, we may be able to make this work better, which might allow for a broader range of values for the Frisch elasticity to be available.  But my recommendation is to limit the values one can choose in Tax Brain and we'll sort out the more esoteric issues later, after adding some more important functionality to the code and improving documentation.

@rickecon @talumbau @MattHJensen

**Comment by MattHJensen** [comment]
Makes sense to me, and check out current-law-policy.json in tax-calculator for an example method of how to specify the allowed range. 

T.J., sounds like this will need to be a 'hard' validation with error, rather than the 'soft' validation w warning that you just implemented for the microsim inputs.

**Comment by talumbau** [comment]
Yep, that sounds right. I will add a `validation` section to the JSON metadata here:

https://github.com/open-source-economics/OG-USA/blob/master/Python/ogusa/parameters_metadata.json

similar to what is done in Tax-Calculator. That way Jason, Rick, or others can modify these parameters by posting PRs on this repo, rather than the webapp. @jdebacker can you confirm that it is this `upsilon` parameter that should be constrained to be at a minimum 0.1 and a maximum of 0.8? Just want to make sure that's the correct parameter.

**Comment by talumbau** [comment]
@jdebacker @MattHJensen see this PR for implementation:

https://github.com/open-source-economics/OG-USA/pull/186

**Comment by MattHJensen** [comment]
@jdebacker, I'm a bit confused after remembering that the Frisch elasticity used in the 10% rate cut paper was 1.5.

**Comment by jdebacker** [comment]
@MattHJensen, If you are confused about the new baseline value of 0.4, let
me explain two things:
1) The 10% rate cut paper carries over a typo from the wealth tax paper.
It should have read that the *inverse Frisch elasticity* parameter was 1.5
- so a Frisch of 1/1.5=0.67 was used (sometimes on write the inverse Frisch
instead given the functional form of the constant Frisch elasticity
function).
2) I pulled the value down a bit, citing a couple pieces of peer-reviewed
research (Altonji (1986) and Peterman (2016)) and was influenced to do so
by some conversations at CPEC.

**Comment by MattHJensen** [comment]
Ahh, point 1 clears things up. Sounds good. This paper says 0.4 is the central estimate used by CBO as well: http://www.cbo.gov/sites/default/files/cbofiles/attachments/10-25-2012-Frisch_Elasticity_of_Labor_Supply.pdf.
