### ISSUE TITLE
OG-USA speed up

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#224]
In working out the time path resource constraint issues, I ratcheted down the TPI tolerance from 2e-5 to 1e-9.  This about doubles the run time (close to 4 hours for TPI on my laptop).  However, I do like the tighter tolerances.  

We haven't put too much effort into it, but we should start to think about speed ups for OG-USA.

e.g. are there things that we can vectorize that aren't?  Should we use Numba?  Can we improve initial guesses by using past model solutions/prior iterations (see Issue #177)?  What else?

**Comment by rickecon** [comment]
There are definitely places where we can parallelize the code.

**Comment by talumbau** [comment]
As a reasonable starting point, I started a profiling run on version 0.5.5. I'll put results here.

**Comment by talumbau** [comment]
Hmm.. well it was low effort to produce the profile result, but I don't know how informative it is. I'm viewing the results with [snakeviz](https://jiffyclub.github.io/snakeviz/) . The top-level graphic shows as follows:

<img width="1005" alt="screen shot 2016-06-28 at 1 32 40 pm" src="https://cloud.githubusercontent.com/assets/1891418/16427876/17fb8738-3d35-11e6-85ed-b5499f90ed5e.png">

About 80% of the time is spent in `fsolve`, ~20% in the tax function estimate code. So, my inclination would be to find ways to parallelize calls to `fsolve`, since a 2x improvement in the total time spent in `fsolve` would reduce overall runtime by 40%.

**Comment by jdebacker** [comment]
Thanks @talumbau !  Yes, we do some loops with an fsolve at each iteration in TPI.py.  Those loops can be parallelized to a significant degree.

**Comment by jdebacker** [comment]
TO DO:

- [ ] Use dask or multiprocessing to parallelize loops over `j` in `SS.py` and `TPI.py` modules
- [ ] Use an initial guess that is close
- [ ] Use solutions to previous iteration of "outer loop" as guesses for next iteration in `SS.py` and `TPI.py`

**Comment by jdebacker** [comment]
With PR #363 and PR #362, both the SS and TP solutions have been parallelized with dask and can run on up to 7 different processes on different cores of a single machine or on a distributed system.  The tax function estimation has been parallelized in a way that can run on up to 10 different processes.  This has been a cheap way to speed up the model solution.

Starting values for TPI are updated at each iteration. Finding initial guesses that are close can help somewhat with the first iterations, but won't affect speed so much.  That can be addressed in the future are we look to make sure the model is robust to starting values.
