### ISSUE TITLE
Relax balanced budget requirement 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/OG-USA#239]
Several TaxBrain users, including myself, are eagerly awaiting the ability to specify alternative delayed fiscal closing assumptions in OG-USA. This capability, for instance, would have allowed me to use OG-USA for my 3-part blog series on Trump's tax proposals. As it is, writing about a $10 trillion tax plan and assuming contemporaneous offsetting transfer cuts is a bit tricky.  

This feature would also allow for very interesting analyses such as comparing the effects of a 10% rate reduction and/or some other standardized reform across a variety of fiscal closing assumptions. This type of analysis could be a good fit for NTJ or elsewhere.

**Comment by rickecon** [comment]
@MattHJensen . @jdebacker and I are moving to this right now. We just fixed a major issue (#234) in the tax functions that had sucked up all our time since the Stanford conference. But we did spend time in Palo Alto specifying the method for the balance budget constraint. Now we just have to implement it in the code.

**Comment by MattHJensen** [comment]
Excellent. And congrats on #234!

**Comment by MattHJensen** [comment]
@rickecon and @jdebacker, do you have an estimate for when this issue will be resolved? Given the presidential and congressional election results, the chance of tax reform in 2017 has skyrocketed, and the chance that the reform package will be budget neutral is quite small.  W/o the ability to specify alternative fiscal closing assumptions soon, it is very likely that OG-USA won't be used to inform a major, once in a few decades, tax reform.

**Comment by rickecon** [comment]
@MattHJensen, Shooting for January 15.

**Comment by MattHJensen** [comment]
@rickecon said:

> Shooting for January 15.

That's great news. Thanks for the update.

**Comment by salimfurth** [comment]
Per discussion with @rickecon & @jdebacker, I've been working on coding up the approach that Rick outlined. It's largely working, but I've encountered some issues that are worth thinking about:

0. In the closed economy, even a modest national debt is a huge burden and pushes interest rates up to unrealistic levels. E.g., 40% debt => 8.7% interest rates.
1. As I've coded it, there's no natural non-negativity constraint on K. I put in a safeguard that keeps K positive, and will allow TPI to work past an errant iteration without throwing NaNs. But it doesn't fix the underlying problem.
2. As written, our model has a single interest rate in the economy, r. That's unrealistic, but it's also a modeling challenge: with elastic, high interest rates, the government's debt can spin out of control very quickly. How do other models in this family tackle the implicit portfolio allocation problem here?
3. The change in the government spending rule at tG1 often delivers a huge instantaneous shift in G. The rule is to stabilize D/GDP at a convex combination of (D/GDP)_t-1 and (D/GDP)_ss. However, the pre-tG1 spending levels aren't necessarily keeping D/GDP anywhere close to stable. In extreme cases, I've had G go to -20*GDP or so in order to stabilize D/GDP, which had previously been growing rapidly. Even when D/GDP is fairly stable, however, the rule delivers large, though not insane, jumps in G and D/GDP, although that may indicate that I've made a mistake in coding.
4. We ought to specify a balanced_budget boolean, or maybe something slightly richer like "max_deficit" that constrains G on a period-by-period basis. That would be very simple to code and would be useful for experiments where the model otherwise blows up too quickly.
5. I think @rickecon's writeup might have some time-subscript errors in the middle part of equations 4 & 5. But I haven't had time to completely work through it, and now I'm going away for the weekend & will be out of the loop.

Feel free to look at my code - it's branch sbf_deficit.

Happy New Year!

**Comment by salimfurth** [comment]
Updating: branch sbf_deficit now works fully. I've played around with different values, open & closed economies, and run the default reform.

Regarding the points above:
0. The interest rates aren't as bad as I thought - I had 2-year periods. But they do get pretty high even for reasonable debt loads.
5. @rickecon's writeup was correct after all, unsurprisingly.

The other points stand, particular in regards to the economic content.

Should I open a pull request? I'm expecting that we'll wait til @jdebacker and @rickecon have worked on this problem themselves first.

**Comment by jdebacker** [comment]
@salimfurth - nice work!

I've got the SS solved and am working on the TP now. I have only been checking my results with closed economy.  Maybe wait for me to check my work against yours then you can open PR?

**Comment by salimfurth** [comment]
Sounds great, @jdebacker.

**Comment by rickecon** [comment]
@salimfurth . I am glad the equations were right. I think @jdebacker did an exercise that provided further evidence that the new aggregate resource constraint (30') is right.

**Comment by rickecon** [comment]
@salimfurth @jdebacker . A big issue is creating a flag that gets raised if the policy change creates negative government spending (G_t<0) in either the steady-state or at any point along the equilibrium time path. Negative government spending amounts to the government costlessly importing apples and oranges from some magic island. Solutions are:
1. At this point, we just allow a policy change to create negative government spending, due to G_t's nature as a residual. G_t<0 implies infeasibility given current taxes and transfers. This will be informative to the user that his or her policy change is fundamentally infeasible.
2. In the future, we should add a feature that enforces the zero-lower-bound on G_t by having transfers get reduced once G_t hits zero. This rule should certainly be able to stabilize the debt-to-GDP ratio given that tax revenues are positive.

**Comment by jdebacker** [comment]
@salimfurth - did you get your TPI code to converge?  I'm running your code with a smaller state space (S=40, J=2) and I'm getting some cycling - and lots of flats for negative K.

Other ideas to avoid a negative K?  This can create serious problems.

I did get some code similar to yours to converge over the TP, but I am seeing a resource constraint area in period T that I need to find the source of.

@rickecon and @salimfurth - when we allow this budget closure rule, do we still want the model to be able to be toggled between our old budget closure rule (immediately adjust transfers so budget balances in each period) and this rule?  I wasn't sure if we wanted to even keep the old approach.

**Comment by jdebacker** [comment]
@salimfurth Ok - I must have changed some parameters in your code, because I just ran clean clone of your branch and it looks good.  I couldn't think of a better way to deal with K<0 than what you did, so I say we roll with that and we can change later if we see issues (your warnings will be helpful to diagnose).  

If you would, why don't you open a PR.  I suggest we merge that when it's ok then I'll go back and add a flag so we can toggle between the old balanced budget and this closure rule.  

Sound ok?

cc @rickecon

**Comment by salimfurth** [comment]
Thanks, @jdebacker. I'm not sure why you got cycling - I didn't see that for any parameter values, but it would be helpful to know where it's running into problems.

I'm happy to open a PR. I think we should discuss (here or over email) how this change alters the macroeconomics of the problem.

- I haven't worked on the calibration aspects of the model. In its own terms, the model economy contracts  substantially when initial debt is higher. We impose a bigger multiplier to match a current-income moment. But are we matching any other moments? Do we care about that?
- The model government is paying the market rate of interest. Are we OK with that?

I didn't think through the economics-model interfaces much when we pulled the small_open option. I don't want to drag the model too far from its connections to reality.

cc @rickecon

**Comment by jdebacker** [comment]
@salimfurth:

> I haven't worked on the calibration aspects of the model. In its own terms, the model economy contracts substantially when initial debt is higher. We impose a bigger multiplier to match a current-income moment. But are we matching any other moments? Do we care about that?

I though the initial interest rate was ok.  I think we are fine here.  @rickecon any thoughts?

> The model government is paying the market rate of interest. Are we OK with that?

I say yes,  for now.  We can adjust with another PR later.

> I didn't think through the economics-model interfaces much when we pulled the small_open option. I don't want to drag the model too far from its connections to reality.

Can you clarify the concern here?

**Comment by rickecon** [comment]
@jdebacker @salimfurth , I am just climbing back into this. I got a little snowed this week.

1. I am definitely OK for now with the government paying the market interest rate. I think that is a good simplest starting point. But we can add a wedge between a risk-free interest rate and the market rate (which is also risk free in our deterministic model) later.
2. Unbalanced government budget constraint connects this model more completely to reality. The balanced budget is a knife-edge case that we never see. Initial conditions calibrated to the U.S. will always be some kind of deficit or at very least positive debt levels.

**Comment by salimfurth** [comment]
Thanks, @jdebacker for merging in the unbalanced fiscal policy code (sbf_deficit #253 )

@MattHJensen, this means we are capable of doing basic dynamic scores. However, before anybody writes up the results, I'm going to open a new issue about accurately filling out the model's baseline.

**Comment by jdebacker** [comment]
This has been addressed for sometime.  We can think about alternative rules to close the fiscal gap in the future, but those can be addressed in new issues.
