### ISSUE TITLE
Fiscal policy baseline

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#254]
This issue follows up on #239 
cc'ing @rickecon @jdebacker @MattHJensen 

The fiscal policy baseline currently embodied in OG-USA is made up of numbers picked out of the air that allowed the model to converge. The long-term numbers and transition rules are not a big issue - users shouldn't be reporting results after tG1 (the year when spending is forced up or down to initiate convergence to a user-imposed steady state).

But we do need to decide on a good spending and transfer policy baseline and formalize a clean way for users to implement reforms. There are 3 distinct tasks there, I think:

1. Empirically measure G and T and decide whether the current approach (percent of GDP) is plausible for projections. Some other minor empirical questions fall in here, too.
2. Code those baseline numbers. If we do move away from percent-of-GDP rules of thumb, we will have to think about how to handle the scaling factor.
3. Figure out (or inform those of us who don't know) how to write spending reforms.

This is just my first stab, and I understand the architecture less than Rick & Jason, so feel free to correct me. I'm sure that my employer would be happy to have a paper using this model soon and others may as well.

**Comment by jdebacker** [comment]
@salimfurth thanks for opening this issue.  This is a very useful exercise.

Re 1-2, here's my approach.  I'm using the [OMB Fiscal Year 2017 Historical Tables](https://www.whitehouse.gov/sites/default/files/omb/budget/fy2017/assets/hist.pdf).  
I'll use the following definitions. Transfers = VA Benefits and Services (700) + Income Security (600) + Medicare (570) + Healthcare Services (551). Note that I exclude Social Security from Transfers since we model that component separately in the `theta` parameter.  Government Spending = Total Outlays - Transfers - Net Interest on Debt - Social Security.

I believe that calibrating the percentage-of-gdp values is the way to go to minimize scaling issuing moving between model units and current dollar values (thought with these and our factor adjustment, we should be close - the exception being I don't think there is any way we can get negative real interest rates like we've seen on US gov't debt - debt/gdp ratio and model interest rates won't get us to net interest payments as a share of gdp that we see in 2015 data.

Using 2015 values, I'm finding values for our fiscal parameters of:
```
alpha_T = 0.09
alpha_G = 0.05
initial_debt = 0.59
```

Re 3, I think we might need a call to discuss - I'm not quite sure I know what you are asking.

**Comment by salimfurth** [comment]
Re. 3: it would be helpful to be able to change the path of spending in a reform. It would not necessarily remain a % of GDP.

**Comment by jdebacker** [comment]
Given parameters above, I'm getting a solution, but SS revenue is not enough to keep Gss>0 for any level of SS debt to gdp.

To solve this, I propose we add a corporate tax on our representative firm.  I'll post a new issue to discuss how we might calibrate this.  Currently, the model only applied individual income and payroll taxes - but uses those to finance a fiscal outlays calibration that includes all government spending.

**Comment by jdebacker** [comment]
PR #257 adds a corporate income tax (with a rate of 20% since the representative firm is some average of the corporate and non-corporate business entities).  This helps with the fiscal calibration and Gss is now greater than zero in the SS under the baseline calibration.

I think as we add more detail to the model we can get more serious about this calibration.

**Comment by salimfurth** [comment]
Great, that's a big improvement.

**Comment by salimfurth** [comment]
Following up in this issue: in my first attempt to do a "score" style analysis using OG-USA, I ran into the fact that the spending baseline endogenously changes. Thus, a reform that increases GDP by 1% also increases spending & transfers by 1%. That might be a good approximation of the solution to a general political equilibrium, but scoring only makes sense if we hold policies constant.

I propose to (attempt to) enhance fiscal policy by allowing the user to fix G and T at baseline levels. The reform steady state will have to keep G endogenous because otherwise debt will diverge or, perversely, the model will determine that a tax cut must lead to a lower debt ratio in order to have a steady state supporting baseline G+T.

I'm not confident of my ability to do this, so I might need some help with passing saved files from baseline to reform.

**Comment by salimfurth** [comment]
Meant to cc @jdebacker, @rickecon and @kerkphil in the foregoing.

**Comment by salimfurth** [comment]
This issue is resolved with PR #274. Thanks for merging in, @jdebacker!
