### ISSUE TITLE
Resource constraint error tolerance

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#272]
@jdebacker & @rickecon: I'm running into cases using the wide-tolerance `test` option where the code appears to converge, but the resource constraint fails at the end with an absolute difference that's small, but still bigger than `mindist_TPI`. Have you run into this? It's possible that the resource constraint should be held to a looser standard. Or it's possible that the complexity of my cases or a coding error I've made somewhere is causing the gap.

Thoughts?

**Comment by jdebacker** [comment]
@salimfurth I haven't run to this.  The value of `mindist_TPI = 1e-2` when `test=True` (and `mindist_TPI = 1e-9` when `test=False`.  

Since it's just a test, you might not worry.  You I could be more concerned it the tolerance isn't met with the full blown model.  That could be due to some issue with the code - which your test might be pointing out.

Often times, I have seen the recourse constraint errors not meet the required tolerance just in the period before the SS (with `test=False`). This has pretty much always been a coding error on my part.

**Comment by salimfurth** [comment]
OK, I figured out the problem: the `fiscal.D_G_path` code within the `TPI `loop was using `Y` as one of its arguments, but `Y` was never being updated. Either that needs to be `Ynew `or all the other references need to be `Y`. I've fixed this in a forthcoming PR.
