### ISSUE TITLE
Should 'factor' be pegged to average tax unit income or something else?

### ISSUE THREAD

**Issue by salimfurth** [open-source-economics/OG-USA#289]
One of the free parameters in OGUSA is `factor`, which translates between model dollars and US dollars (what year?). The key equation now is `new_factor=mean_income_data / average_income_model` (SS.inner_loop, line 348). 

Depending on the assumptions of the model, `average_income_model` can be an enormously differing fraction of GDP per capita. In some quick test runs with what I thought were reasonable parameter values, I found ratios of personal income to GDP as high as 122% (this is possible in an open economy) and as low as 71%.

This is not only an issue for the open economy version. In a closed economy, differing assumptions about the steady state debt level and the growth rate both have a substantial impact on the ratio between GDP and personal income.

This isn't an error, per se. But it does introduce some very weird dynamics, and it means that first-period values may not match measured current aggregates. I'm posting this here for posterity and perhaps to spark discussion; I'm not asking for any action to be taken now.

**Comment by jdebacker** [comment]
Hmm.  I think the way we are converting model units to dollars seems ok (these are dollars in the `start_year`, BTW, since we are targeting mean income to the PUF in the start year that is chosen by the user).

But you do raise a good point about the ratio of average income to GDP in the model.  We should look into that to check that it makes sense under our baseline parameterization.

**Comment by jdebacker** [comment]
Closing for now.   I think pinning to average is good, but we should revisit when we do some serious targeting of model levels to national accounts data.
