### ISSUE TITLE
Naming the API

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/OG-USA#410]
The new API currently has a module called `pb_api.py` and a class called `Specifications`.  

Since PolicyBrain maybe phasing out (?) and OG-USA will be part of the [PSL](https://github.com/open-source-economics/PSL-Core), perhaps a name like `ogusa_api.py` or `psl_api.py` makes more sense.  @hdoupe, thoughts?

I also suggest renaming of the `Specifications` class to something like `Parameters`. Any thought on this @rickecon ?

**Comment by hdoupe** [comment]
@jdebacker asked:

> Since PolicyBrain maybe phasing out (?) and OG-USA will be part of the PSL, perhaps a name like `ogusa_api.py` or `psl_api.py` makes more sense. @hdoupe, thoughts?

I think `pb_api.py` should be renamed. If you are thinking about renaming the class to `Parameters`, you could rename the module `parameters.py`. However, this could be a little confusing since there's already a `parametersbase.py`. On the other hand, I don't think anyone will directly use `parametersbase.py`. So, it may not be too much of an issue. If you rename it `parameters.py` people would use it like:

```
from ogusa.parameters import Parameters
```

I think that makes more sense than 

```
from ogusa.ogusa_api import Parameters
```

I hesitate to name the module `psl_api.py` because I think it would be better to think of the API as a good way for people to interact with your project in general and not something that's defined by some other entity.

What other names are you thinking?

**Comment by jdebacker** [comment]
Ok - we defined to go with `parameters.py` as the module and keep `Specifications` as the class.
